### ISSUE TITLE
Problem with migration of mutant.db.deletion.CASCADE_MARK_ORIGIN in South

### ISSUE THREAD

**Issue by pikhovkin** [charettes/django-mutant#26]
```
python manage.py schemamigration app_name --init
```
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File ".../local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File ".../local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File ".../local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File ".../local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File ".../local/lib/python2.7/site-packages/south/management/commands/schemamigration.py", line 151, in handle
    for action_name, params in change_source.get_changes():
  File ".../local/lib/python2.7/site-packages/south/creator/changes.py", line 460, in get_changes
    model_defs = freeze_apps([self.migrations.app_label()])
  File ".../local/lib/python2.7/site-packages/south/creator/freezer.py", line 37, in freeze_apps
    model_defs[model_key(model)] = prep_for_freeze(model)
  File ".../local/lib/python2.7/site-packages/south/creator/freezer.py", line 73, in prep_for_freeze
    fields = modelsinspector.get_model_fields(model, m2m=True)
  File ".../local/lib/python2.7/site-packages/south/modelsinspector.py", line 413, in get_model_fields
    args, kwargs = introspector(field)
  File ".../local/lib/python2.7/site-packages/south/modelsinspector.py", line 373, in introspector
    kwargs[kwd] = get_value(field, defn)
  File ".../local/lib/python2.7/site-packages/south/modelsinspector.py", line 292, in get_value
    return value_clean(value, options)
  File ".../local/lib/python2.7/site-packages/south/modelsinspector.py", line 350, in value_clean
    value = options['converter'](value)
  File ".../local/lib/python2.7/site-packages/south/modelsinspector.py", line 54, in convert_on_delete_handler
    raise ValueError("%s was not recognized as a valid model deletion handler. Possible values: %s." % (value, ', '.join(f.__name__ for f in (models.CASCADE, models.PROTECT, models.SET, models.SET_NULL, models.SET_DEFAULT, models.DO_NOTHING))))
ValueError: <function CASCADE_MARK_ORIGIN at 0x1cfc758> was not recognized as a valid model deletion handler. Possible values: CASCADE, PROTECT, SET, set_on_delete, SET_DEFAULT, DO_NOTHING.
```

Found that the problem occurs when trying to create a South migration scheme for ModelDefinitionAttribute.

Please, help solve this problem.

**Comment by charettes** [comment]
Closing since South support is deprecated.
