### ISSUE TITLE
how to dynamic create foreignkeyfield

### ISSUE THREAD

**Issue by caoguangyao** [charettes/django-mutant#50]
hi charettes

I read https://gist.github.com/charettes/5670245 and to run it, when code to

> ForeignKeyDefinition.objects.create(
>     model_def=street_model_def, name='city', to=city_model_def.model_class()
> )

it go exception 

> "ForeignKeyDefinition.to" must be a "ContentType" instance.

I use django 1.9.7 and python 2.7 

it seems the 'to' paramter is wrong  ,I change to=city_model_def and it works

BTW,how to add self related foreignkey field?
when I register field on admin page it make the project crash.

```
AttributeError: 'module' object has no attribute 'FieldDefinition'
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x103b555f0>
Traceback (most recent call last):
  File "/Users/caoguangyao/Desktop/venv/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/caoguangyao/Desktop/venv/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/Users/caoguangyao/Desktop/venv/lib/python2.7/site-packages/django/core/management/base.py", line 472, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
dynamic.TagTree.parent: (fields.E302) Reverse accessor for 'TagTree.parent' clashes with field name 'TagTree.parent'.
    HINT: Rename field 'TagTree.parent', or add/change a related_name argument to the definition for field 'TagTree.parent'.
dynamic.TagTree.parent: (fields.E303) Reverse query name for 'TagTree.parent' clashes with field name 'TagTree.parent'.
    HINT: Rename field 'TagTree.parent', or add/change a related_name argument to the definition for field 'TagTree.parent'.

System check identified 2 issues (0 silenced).


```

**Comment by charettes** [comment]
@caoguangyao I'm not sure if it's relevant anymore but you need to provide a `related_name` on `ForeignKeyDefinition` creation just like the checks hint at. I'll fix the documentation bug about `to` right away.

**Comment by charettes** [comment]
Documentation fixed. Thanks for the report.
