### ISSUE TITLE
Error in migration

### ISSUE THREAD

**Issue by alust** [charettes/django-mutant#53]
Hi!

I've created a simplest application that uses mutant (just made a project wuth django-admin startproject and added 'mutant' to INSTALLED_APPS).

However creating migrations produces this error:

```
# ./manage.py makemigrations
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/state.py", line 376, in from_model
    clones = field.clone()
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py", line 458, in clone
    return self.__class__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mutant/db/fields/generic.py", line 13, in __init__
    'mutant.FieldDefinition', on_delete=on_delete, *args, **kwargs
TypeError: __init__() got multiple values for argument 'polymorphic_type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/makemigrations.py", line 150, in handle
    ProjectState.from_apps(apps),
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/state.py", line 188, in from_apps
    model_state = ModelState.from_model(model)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/state.py", line 384, in from_model
    e,
TypeError: Couldn't reconstruct field content_type on mutant.FieldDefinition: __init__() got multiple values for argument 'polymorphic_type'

```

A quick look to the sources shows that `PolymorphicTypeField.__init__` method has following signature (polymodels/fields.py, line 82):

    def __init__(self, polymorphic_type, *args, **kwargs):

It is called from `FieldDefinitionTypeField.__init__` method (mutant/db/fields/generic.py, line 11):

        super(FieldDefinitionTypeField, self).__init__(
            'mutant.FieldDefinition', on_delete=on_delete, *args, **kwargs
        )

So 'mutant.FieldDefinition' is passed as 'polymorphic_type' parameter while kwargs dictionary also has 'polymorphic_type' key with value 'mutant.FieldDefinition', that causes the error.

Is it a bug or I missed anything in the configuration?

django-mutant: 0.2.1
django: 1.10.3
python: 3.5.2

-- 
Alexei

**Comment by kamalseisy** [comment]
I have the same error
I tested with django 1.8.16 and 1.10.6

**Comment by nichcz** [comment]
I had same problem. Fixed with explicit version installation based on Requires Distributions on pypi:
```
pip install django-polymodels==1.4.6a3
pip install django-mutant==0.3.0a4
```
