### ISSUE TITLE
How to make full use of django-mutant(Simply describe how it works?)

### ISSUE THREAD

**Issue by NoraGithub** [charettes/django-mutant#55]
Hi, @charettes .
Thanks for your great job for django-mutant.
I am trying to make use following the steps [here-A getting started guide](http://integricho.github.io/2013/07/22/mutant-introduction/).
However, here comes some issues :
1. 
`__init__() missing 1 required positional argument: 'queryset'`
which is caused from [github repo of "A getting started guide"](https://github.com/NoraGithub/mutant-sample-app/blob/master/mutanttest/apps/mutantgui/forms.py)
```python
def get_field_def_form(field_type_pk, model_def_queryset):
    '''
    to dynamically create self.form_class for FIELDCREATE view
    '''
    class Meta:
        model = get_mutant_type(field_type_pk)

    form_attrs = {
        'Meta': Meta,
        'content_type': FieldDefinitionTypeField(widget=forms.HiddenInput),#this line,
        'model_def': forms.ModelChoiceField(queryset=model_def_queryset,
                                            widget=forms.HiddenInput)
    }

    return type('FieldDefinitionForm', (forms.ModelForm,), form_attrs)
```
line 23
` 'content_type': FieldDefinitionTypeField(widget=forms.HiddenInput),`
I don't know how to fix it while I want to **dynamically** create a model/table.(I clearly know I SHOULD add a queryset to fix it , but ,how to generate a queryset for the field_type? )

2.
Also, I found that there are  2 `FieldDefinitionTypeField` class in your repo ,is that a kind of typo ? One is located ["db.fields."](https://github.com/charettes/django-mutant/blob/master/mutant/db/fields/generic.py), the other is located ["mutant.forms"](https://github.com/charettes/django-mutant/blob/master/mutant/forms.py).

3.
Lastly. How to fill data into a table(OF COURCE BY DJANGO, NOT BY PYTHON/MYSQL ONLY), while there is no a related model in the admin and no way to initialize an instance?(We can just see ModelDefinition FieldDefinition in admin,but a specific model mapping to the model. I don't know whether the questions is clear)

4.
How to register a dynamic class? While I register it by 
`admin.site.register(models.ModelDefinition.objects.filter(app_label='app_label',model='model',object_name='object_name')[0].construct(),modelAdmin)`
I get the error as `AttributeError: 'MutantConfig' object has no attribute 'state_handler'`.
I just have no idea how to make use of it.

Here's the log:
>Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x1138eb400>
Traceback (most recent call last):
  File "/Users/NoraChan/Desktop/geekhacker.tech/web_virtualenv/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/NoraChan/Desktop/geekhacker.tech/web_virtualenv/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/Users/NoraChan/Desktop/geekhacker.tech/web_virtualenv/lib/python3.4/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/NoraChan/Desktop/geekhacker.tech/web_virtualenv/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/NoraChan/Desktop/geekhacker.tech/web_virtualenv/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/NoraChan/Desktop/geekhacker.tech/web_virtualenv/lib/python3.4/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/NoraChan/Desktop/geekhacker.tech/web_virtualenv/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/Users/NoraChan/Desktop/geekhacker.tech/web_virtualenv/lib/python3.4/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/Users/NoraChan/Desktop/geekhacker.tech/web_virtualenv/lib/python3.4/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Users/NoraChan/Desktop/geekhacker.tech/web_virtualenv/lib/python3.4/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/Users/NoraChan/Desktop/geekhacker.tech/web_virtualenv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/NoraChan/Desktop/geekhacker.tech/Datadriven_Website/dataset/admin.py", line 18, in <module>
    obj = models.ModelDefinition.objects.filter(app_label='explorer',model='ad0',object_name='ad0')[0].construct()
  File "/Users/NoraChan/Desktop/geekhacker.tech/web_virtualenv/lib/python3.4/site-packages/django/db/models/query.py", line 295, in __getitem__
    return list(qs)[0]
  File "/Users/NoraChan/Desktop/geekhacker.tech/web_virtualenv/lib/python3.4/site-packages/django/db/models/query.py", line 256, in __iter__
    self._fetch_all()
  File "/Users/NoraChan/Desktop/geekhacker.tech/web_virtualenv/lib/python3.4/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/NoraChan/Desktop/geekhacker.tech/web_virtualenv/lib/python3.4/site-packages/django/db/models/query.py", line 66, in __iter__
    obj = model_cls.from_db(db, init_list, row[model_fields_start:model_fields_end])
  File "/Users/NoraChan/Desktop/geekhacker.tech/web_virtualenv/lib/python3.4/site-packages/django/db/models/base.py", line 565, in from_db
    new = cls(*values)
  File "/Users/NoraChan/Desktop/geekhacker.tech/django-mutant/mutant/models/model/__init__.py", line 189, in __init__
    self._model_class = self.model_class().model
  File "/Users/NoraChan/Desktop/geekhacker.tech/django-mutant/mutant/models/model/__init__.py", line 304, in model_class
    model_class = self.construct(force_create, model_class)
  File "/Users/NoraChan/Desktop/geekhacker.tech/django-mutant/mutant/models/model/__init__.py", line 274, in construct
    state_handler.set_checksum(self.pk, checksum)
  File "/Users/NoraChan/Desktop/geekhacker.tech/django-mutant/mutant/state/utils.py", line 10, in __getattribute__
    handler = apps.get_app_config('mutant').state_handler
AttributeError: 'MutantConfig' object has no attribute 'state_handler'

If you can help answer it or give some direction/tips, I would appreciate so much.

**Comment by NoraGithub** [comment]
1. I USER ContentType.objects.all() as the Queryset

3. ModelDefinition.construct did that.

**Comment by NoraGithub** [comment]
Will there be because that  django-mutant relies on contenttype and at `import` time, contenttype hadn't constructed yet, and then here came this the 4th issue?

**Comment by NitayRabi** [comment]
+1 same here with the state handler.

**Comment by Hamza-abughazaleh** [comment]
please can you help me how to register the model created to admin?
