### ISSUE TITLE
Unable to perform migration

### ISSUE THREAD

**Issue by sathiz1993** [charettes/django-mutant#58]
I have installed django-mutant and performed CRUD operations on Table Definition, Field Definitions and on Dynamically created models. But when I try to do migration after the above operations it returns **TypeError** in **mutant.FieldDefinition**. Below is the traceback
```
python onboard/manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, boolean, contenttypes, file, mutant, numeric, related, sessions, temporal, text, web
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "/media/sathish/Study/Office/django-onboard/venv/lib/python3.4/site-packages/django/db/migrations/state.py", line 411, in from_model
    fields.append((name, field.clone()))
  File "/media/sathish/Study/Office/django-onboard/venv/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 470, in clone
    return self.__class__(*args, **kwargs)
  File "/media/sathish/Study/Office/django-onboard/venv/lib/python3.4/site-packages/mutant/db/fields/generic.py", line 12, in __init__
    'mutant.FieldDefinition', on_delete=on_delete, *args, **kwargs
TypeError: __init__() got multiple values for argument 'polymorphic_type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "onboard/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/media/sathish/Study/Office/django-onboard/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/media/sathish/Study/Office/django-onboard/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/media/sathish/Study/Office/django-onboard/venv/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/media/sathish/Study/Office/django-onboard/venv/lib/python3.4/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/media/sathish/Study/Office/django-onboard/venv/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 180, in handle
    ProjectState.from_apps(apps),
  File "/media/sathish/Study/Office/django-onboard/venv/lib/python3.4/site-packages/django/db/migrations/state.py", line 222, in from_apps
    model_state = ModelState.from_model(model)
  File "/media/sathish/Study/Office/django-onboard/venv/lib/python3.4/site-packages/django/db/migrations/state.py", line 416, in from_model
    e,
TypeError: Couldn't reconstruct field content_type on mutant.FieldDefinition: __init__() got multiple values for argument 'polymorphic_type'
```

**Comment by charettes** [comment]
Make sure you update to the latest `django-polymorphic` version.

https://github.com/charettes/django-mutant/issues/53#issuecomment-292441774

**Comment by sathiz1993** [comment]
I have installed django-mutant via pip. The version installed was 
```
django-mutant==0.2.1
django-polymodels==1.4.6
```

I encountered the error the above. But when I upgraded the package manually the error is fixed. Now the version is
```
django-mutant==0.3a4
django-polymodels==1.4.6a3
```
Could you move this package to PyPI
